title: JOBDOH
email: info@jobdoh.com
description: > # this means to ignore newlines until "baseurl:"
  Need pre-screened quick or last-minute temporary help or work? Download JOBDOH today, an award-wining smart booking platform to solve your temp work hiring needs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jobdoh.github.io" # the base hostname & protocol for your site

gems:
  - jekyll-paginate
  - jekyll-redirect-from

permalink: pretty

excerpt_separator: <!--more-->

paginate: 2
paginate_path: "/blog/:num/"

markdown: kramdown

prose:
  rooturl: '_posts'
  siteurl: 'http://jobdoh.github.io'
  media: 'media'
  metadata:
    _posts:
      - name: "published"
        label: "published"
        field:
          element: "checkbox"
      - name: "category"
        field:
          element: "select"
          options:
            - name: "Blog"
              value: "blog"
            - name: "Press"
              value: "press"
      - name: "section"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog-post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "redirect_from"
        field:
          element: "text"
          label: "Redirect From"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
